### ISSUE TITLE
Unsupported Authenticator

### ISSUE THREAD

**Issue by Ciaran0** [websudos/phantom#242] opened 2015-05-13 09:42 UTC
Im getting the error 
Unsupported Authenticator org.apache.cassandra.auth.PasswordAuthenticator
using phantom-dsl 1.8.0
is there any known solutions?

```
object CustomCassandraManager extends DefaultCassandraManager{

  def certOptions() : SSLOptions = {
    val context = SSLContext.getInstance("TLS")
    context.init(null, Array[TrustManager](new TrustAllTrustManager) , new SecureRandom())
    new SSLOptions(context, SSLOptions.DEFAULT_SSL_CIPHER_SUITES)
  }
  override protected[this] def createCluster: Cluster = {
    val ip = ""
    Cluster.builder()
      .addContactPoint(ip)
      .withAuthProvider(new PlainTextAuthProvider("", ""))
      .withSSL(certOptions())
      .build()
  }
}

trait Connector extends SimpleCassandraConnector {
  implicit val keySpace = new KeySpace("")

  override val manager = CustomCassandraManager
}
```

**Comment by alexflav23** [comment] 2015-05-13 11:20
@Ciaran0 That's quite strange. I will have a word with someone on the Cassandra team to double check how this should behave and we will then make sure it's properly implemented. This doesn't look phantom specific however.

The cluster builder and everything connection related is still handled by the Datastax Java Driver, which means there is a chance you might be using wrong options for your node or something like that. As far as I know, authentication is Datastax Enterprise only, please confirm you do indeed have a license for that and a running DSE before attempting to use passwords(or correct me if I am wrong).

**Comment by Ciaran0** [comment] 2015-05-14 13:49
Yes its a licensed and running dse.
In another application we use the same code and it works fine.
The driver we use is
"com.datastax.cassandra" % "cassandra-driver-core" % "1.0.2-dse2 

thanks for looking into this

**Comment by alexflav23** [comment] 2015-05-15 20:57
Hi @Ciaran0,

Ok I see what the problem is now. Let me have a look into that this weekend and see what exactly is causing the discrepancy.

Regards,

**Comment by alexflav23** [comment] 2015-06-13 22:44
Hi @Ciaran0,

We've fixed most issues, however DSE support is not and will not be available in the open source version of phantom. We have another product coming along, phantom-enterprise, which will fix any integration issues with OpsCenter, DSE, Spark and many more.

It won't be out for another month or more, but I do promise to let you know as soon as we have a stable release out, things are currently going through heavy internal testing.

Regards.

**Comment by alexflav23** [comment] 2015-07-16 11:30
Hi @Ciaran0 ,

This is now fixed in the `phantom-enterprise` roadmap. An initial release will be out in September, to give you a very powerful integration with all DSE features, including Spark SQL support via our `morpheus` SQL engine, Solr integration, automated Solr schema generation, and much more.

I will close this issue for now since it will not be part of any OSS release.

Regards.

**Closed by alexflav23** 2015-07-16 11:30 UTC
