### ISSUE TITLE
select will not materialize to SelectQuery 

### ISSUE THREAD

**Issue by raam86** [websudos/phantom#355] opened 2015-11-18 18:09 UTC
writing 
```
CFNAME.select
``` 
return 

`ROOTSELECTBLOCK` that doesn't have a where definition 
while distinct and count returns SelectQuery which does have a where method.

Seems like I am missing something but what? This worked fine on 1.5.0

**Comment by alexflav23** [comment] 2015-11-18 18:50
Hi @raam86 ,

You are missing one of the following:

- The `import com.websudos.phantom.dsl._` import at the top, which has an implicit conversion from `RootSelectBlock` to `SelectQuery.`
- An implicit `keySpace` definition in the scope where you are trying to compose the query.
- An implicit `session` definition in the scope where you are running the query.

The former 2 are fixed by using connectors, revisit [this blog post](http://blog.websudos.com/2015/04/04/a-series-on-phantom-part-1-getting-started-with-phantom/) for more details or have a look at the tests/phantom-activator-template.

Hope this helps!

**Comment by raam86** [comment] 2015-11-18 19:03
@alexflav23 Thank you for your help. 

I actually tried running with distinct and got the keySpace error. after running with distinct I was able to use the dsl as usual. 

Maybe it was the keySpace but it failed too early? 

Anyways,
Cheers,

**Comment by alexflav23** [comment] 2015-11-18 23:42
Hi @raam86,

I think you have successfully circumvented all written documentation on phantom, which I believe may be the root cause of this. The approach you are taking is dangerous as you are introducing blocking behaviour to a Netty channel.

`val connector = ContactPoints(hosts).keySpace("test")`

That will just give you the inner trait `connector.Connector` that you can mix in anywhere you need the `implicit session` and `implicit keyspace`. Use database objects as intended by the framework.

**Closed by alexflav23** 2015-11-18 23:42 UTC

**Comment by raam86** [comment] 2015-12-06 10:57
Thanks alex I would love a link ContactPoints docs.

**Comment by alexflav23** [comment] 2015-12-06 13:09
HI @raam86,

The blog post in question is [here](http://blog.websudos.com/2015/04/04/a-series-on-phantom-part-1-getting-started-with-phantom/).

Regards.

**Comment by raam86** [comment] 2015-12-22 17:47
Thanks. That was helpful
