### ISSUE TITLE
CQL to Set Consistency Level Seems Obsolete 

### ISSUE THREAD

**Issue by nosheenzaza** [websudos/phantom#256] opened 2015-05-26 09:32 UTC
I am using phantom 1.8.4 with Cassandra 2.0.8, in an experimental 3-node cluster setting. I modified `SimpleRecipes` example to set a consistency level for Insert query like this:

```
def insertRecord(recipe: Recipe): ScalaFuture[ResultSet] = {
    insert.value(_.id, recipe.id)
      .value(_.title, recipe.title)
      .value(_.author, recipe.author)
      .value(_.description, recipe.description)
      .value(_.ingredients, recipe.ingredients)
      .value(_.name, recipe.name)
      .ttl(150.minutes.inSeconds)
      .consistencyLevel_=(ConsistencyLevel.ALL)
      .future()
  }
```

I see that the query built is:
```
CQLQuery(INSERT INTO phantom_examples.nosheen_recipes (ident, title, author, description, ingredients, name) 
VALUES(6f9b8507-cc06-4355-bac7-1ecfe0b260c7, 'Yummy Chicken', 'Nosheen Zaza', 'Grill on wooden skewers', { 'chicken', 'spice', 'more spice' }, 'Grilled Chicken') 
USING TTL 9000 CONSISTENCY ALL)
```
I know that setting consistency level in USING clause like this is not supported in CQL 3, used in 2.0.* and 2.1.* versions in Cassandra. When running my code, I get an error.

Looking at Phantom's source code it does not seem like queries are built differently depending on CQL version. What is the problem here? And how can I set the consistency level correctly?

**Comment by alexflav23** [comment] 2015-05-26 09:36
Hi @nosheenzaza,

This is definitely a bug on our end, thank you for reporting it.  We will include the bug fix in 1.9.0 to address the issue and our apologies for the inconvenience.

It will be released alongside all the new 1.9.0, including the new connectors framework and other niceties, hopefully by the end of this week or mid next week. We will also aim to push a quick fix for this shortly as we already have the means to introduce per version behaviour easily.

Regards,

**Comment by alexflav23** [comment] 2015-07-29 20:51
Hi @nosheenzaza  ,

Currently the consistency level in the latest versions of the CQL protocol is set in a whole new way, in a `use` clause at protocol level. So you would have to execute two queries to effectively set the level of a query:

```scala

USE CONSISTENCY QUORUM;

UPDATE keyspace.table WHERE .. bla
```

This is somewhat misleading and a bit dangerous to do on the client because we would need to automatically batch queries and execute two things at once. There is also a problem is permanently having to reset the consistency level currently in use, in the event the "next" query does not have a consistency level set. So for every query, you would now have to run 3 queries, to set the consistency level, execute the actual query, and then unset it.

If you would use the Java driver, setting the consistency level produces the exact same query and having never set it in the first place, which means setting the level on a per query basis is no longer a possibility. We are very open to debate about this but our current understanding is that the level settings have indeed changed.

I know you've been doing work to research this in more depth, do you have any further insights we are currently missing on? As far as it's visible from here per query consistency level should be deprecated and removed for all protocol versions greater than 3.1 and we should do the exact same thing as the Datastax Java Driver does, which is to leave the query unchanged for protocol versions newer than 3.1.0

Regards,
Flavian

**Comment by nosheenzaza** [comment] 2015-07-29 21:42
Hello Flavian,

The following is what I remember on top of my head but I will try to look more into it tomorrow. 

Looking at [this issue] (https://issues.apache.org/jira/browse/CASSANDRA-4734) and [examples of using the Java driver](http://docs.datastax.com/en/developer/java-driver/2.1/common/drivers/reference/cqlStatements.html), I understand that clients should still allow setting the consistency level per statement, however not by allowing the user to pass the CQL query string with USING part, but by setting it as a parameter to the CQL statement, exactly like you do in your driver currently. The relevant point here is to avoid having to parse CQL statements as a string in order to figure out the specified consistency. I would assume this makes setting the consistency in phantom behind the scenes even simpler, because you do not have to append the consistency as a substring to your CQL statement string and then ask the session to execute it. You can instead generate the CQL statement string, pass along the consistency level then ask the session to execute it with the specified level. I am not how the session associates a consistency level to a statement behind the scenes, but I assume this is unimportant for the goal of updating phantom. 

In summery, I believe phantom's interface should remain the same, and some refactoring should be done to the code that assembles the CQL query string. What do you think?

**Comment by alexflav23** [comment] 2015-07-29 22:31
Hi @nosheenzaza,

That sounds like the perfect plan except I seriously fail to see where the Datastax Java driver sets the CQL internally. The cluster has some query options and we can also use `SimpleStatement` forwarding internally to try and forward the consistency level definitions invisibly.

This should hopefully be fixed with some more iteration done at more reasonable times of the day. Looks like this should be addressable after all, it's been a problem for some time. Many thanks for your advice and contributions!

Regards,

**Comment by alexflav23** [comment] 2015-08-16 15:50
Hi @nosheenzaza,

I've finally had the time to do something about this and a pull request is now available [here](https://github.com/websudos/phantom/pull/304). Wouldn't mind some feedback on the implementation, which feels slightly hackish in an attempt to avoid having to make backwards incompatible changes.

Right now even though `null` defaults are propagated around, no queries in the tests or any code whatsoever was exposed to the end user and the change is invisible. Perhaps there are still improvements to be made while keeping this behaviour and avoiding the rather ugly solution at the same time.

Regards.

**Comment by alexflav23** [comment] 2015-08-23 19:27
@nosheenzaza Phantom 1.12.2 is in the process of being synced to Maven Central, we've fixed support for consistency levels in all queries and added per CQL protocol version mechanisms that are backwards compatible with old versions of Cassandra as well. The issue is now fixed and can be closed. The tag is `1.12.2` so the diff is easy to review if need be.

**Closed by alexflav23** 2015-08-23 19:27 UTC

**Comment by nosheenzaza** [comment] 2015-08-24 09:08
Many many thanks! I did not have the time to have a look yet. Will try to do it over weekend.

**Comment by jfklingler** [comment] 2015-10-30 15:33
Hello @alexflav23,

I'm still seeing this problem with phantom 1.12.2 and 1.12.3 on Cassandra 2.0.12.274/DSE 4.6.2 (CQL spec 3.1.1). Is there a flag I need to set somewhere to enable the correct behavior? (I admit I haven't looked at tag diffs for 1.12.2 or 1.12.3)

When I execute the query
```
insert
  .value(_.job_id, jobId)
  .value(_.checksum, checksum)
  .consistencyLevel_=(ConsistencyLevel.QUORUM)
  .ttl(ttl)
  .future()
```
I get the following exception
```
com.datastax.driver.core.exceptions.SyntaxError: line 1:87 missing EOF at 'USING'
 	at com.datastax.driver.core.Responses$Error.asException(Responses.java:122) ~[cassandra-driver-core-2.2.0-rc3.jar:na]
 	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:120) ~[cassandra-driver-core-2.2.0-rc3.jar:na]
 	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:186) ~[cassandra-driver-core-2.2.0-rc3.jar:na]
 	at com.datastax.driver.core.RequestHandler.access$2300(RequestHandler.java:45) ~[cassandra-driver-core-2.2.0-rc3.jar:na]
 	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:754) ~[cassandra-driver-core-2.2.0-rc3.jar:na]
 	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:576) ~[cassandra-driver-core-2.2.0-rc3.jar:na]
 	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:994) ~[cassandra-driver-core-2.2.0-rc3.jar:na]
 	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:916) ~[cassandra-driver-core-2.2.0-rc3.jar:na]
...(netty stuff)
```

Thanks,
JFK

**Comment by jfklingler** [comment] 2015-10-30 20:29
If it helps any, the query string that is generated by phantom is
```
INSERT INTO docs.contents (job_id, checksum) VALUES('DDBFC8A4-9173-41DB-B42F-076B543E6CE9', '5a73b427f04db5ff7af8703063923a0a') USING CONSISTENCY QUORUM;
```

**Comment by jfklingler** [comment] 2015-11-02 15:01
So I tried another version of DSE (Cassandra 2.1.11.872 | DSE 4.7.4 | CQL spec 3.2.1) and it seems to work now. Not sure what the issue was with the other version.
