### ISSUE TITLE
Stuck making testing work with embedded Cassandra

### ISSUE THREAD

**Issue by juanjovazquez** [websudos/phantom#251] opened 2015-05-19 10:23 UTC
Hi all, It's probably a silly mistake but I get a connection refused error when I run a simple test based on CassandraFlatSpec (i.e. a SimpleCassandraTest). It seems that embedded Cassandra is starting properly listening for connections on port 9142:

12:10:05.698 [pool-28-thread-1] INFO  o.apache.cassandra.transport.Server - Starting listening for CQL clients on localhost/127.0.0.1:9142...

But, after that, the datastax client driver is trying to connect to 9042 port instead of 9142:

Exception encountered when invoking run on a nested suite - All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.TransportException: [localhost/127.0.0.1:9042] Cannot connect))

My test is just a dummy one mix-in a trait like this:

trait PhantomTest extends CassandraFlatSpec with KeySpaceDefinition

When I use my own local Cassandra instance listening on port 9042 is working like a charm.

Thanks in advance for your help.

**Comment by alexflav23** [comment] 2015-05-22 14:22
Hi @juanjovazquez,

Thank you for reporting this. It sounds like a small error indeed, it will be reviewed and we will keep you up-to-date.

Regards.

**Comment by juanjovazquez** [comment] 2015-05-22 14:48
Thanks @alexflav23. For the time being, I keep testing with my own local Cassandra instance.

**Comment by mmatloka** [comment] 2015-05-26 11:34
I have exactly the same problem.

**Comment by alexflav23** [comment] 2015-05-26 11:43
@juanjovazquez @mmatloka In Phantom 1.9.0 there will be a new `phantom-sbt` plugin available that allows you to make SBT automatically start Embedded Cassandra before any test is run. The current mechanism was replaced as it was very unreliable.

Then in your tests you can simply override the connector and tell it to always use the embedded flavour. `1.9.1` is already on Bintray, I will try and publish the working branch with the new README as well, which describes how to use the new stuff.

**Comment by mmatloka** [comment] 2015-05-26 11:53
@alexflav23 thx for quick response. I am trying to use 1.9.1 now and it seems one package is missing `com.websudos#util-testing_2.11;0.9.6: not found`

**Comment by mmatloka** [comment] 2015-05-26 12:10
Thx, I see it is already uploaded :)

**Comment by mmatloka** [comment] 2015-05-26 14:56
@alexflav23 I have seen `phantom-sbt` is in bintray aswell, but it seems to be incorrectly published. When added via `addSbtPlugin("com.websudos" % "phantom-sbt" % "1.9.1")` sbt throws `https://dl.bintray.com/websudos/oss-releases/com/websudos/phantom-sbt_2.10_0.13/1.9.1/phantom-sbt-1.9.1.jar` although its under `https://dl.bintray.com/websudos/oss-releases/com/websudos/phantom-sbt/1.9.1/` .

**Comment by juanjovazquez** [comment] 2015-06-04 09:55
@mmatloka the same happened to me. I'm not being able to resolve the plugin. What has your workaround been?

**Comment by mmatloka** [comment] 2015-06-05 09:35
@juanjovazquez I have not found a workaround. Waiting for @alexflav23  ;)

**Comment by hmrajas** [comment] 2015-06-08 06:15
https://docs.wso2.com/display/DSS322/Cassandra+Sample
i got same error because i'm not running the Cassandra server before run the sample

**Comment by elmalto** [comment] 2015-06-12 17:38
I ran into the same issue and created my "own" implementation (Using my DBConnector which has simple test detection and uses ip/port accordingly). Removed my play framework code, hope I didn't forget any in it ... in case you need a play fake application, start ```Play.start(FakeApplication())``` right after the self type in the trait

```
package services.cassandra

import java.io.IOException
import java.net.{InetAddress, InetSocketAddress, Socket}

import com.datastax.driver.core.{Cluster, Session}
import com.websudos.phantom.connectors._
import com.websudos.phantom.testkit.suites.CassandraSetup
import org.scalatest.concurrent.{AsyncAssertions, PatienceConfiguration, ScalaFutures}
import org.scalatest.{Assertions, BeforeAndAfterAll, Suite, _}

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.control.NonFatal

trait MyCassandraTest extends ScalaFutures
with SimpleCassandraConnector
with Assertions
with AsyncAssertions
with BeforeAndAfterAll
with BeforeAndAfter
with CassandraSetup
with SequentialNestedSuiteExecution {
  self: BeforeAndAfterAll with Suite =>
  override implicit val keySpace = KeySpace("my_keyspace")
  /**
   * The default timeout value for phantom tests, passed implicitly to the testing framework.
   * @return The default timeout value.
   */
  implicit def patience: PatienceConfiguration.Timeout = timeout(5 seconds)

  override val manager: CassandraManager = CassandraProperties.manager

  override implicit lazy val session: Session = {
    manager.initIfNotInited(keySpace.name)
    DBConnector.session
  }

  implicit lazy val context: ExecutionContext = global

  override def beforeAll() {
    super.beforeAll()
    setupCassandra()
    manager.initIfNotInited(keySpace.name)
  }
}

object CassandraProperties {
  val ZookeeperEnvironmentString: String = "TEST_ZOOKEEPER_CONNECTOR"
  val DefaultHosts = Set(new InetSocketAddress("localhost", 9142))
  val Localhost = Set(new InetSocketAddress("localhost", 9142))
  lazy val manager = new MyCassandraManager
}

class MyCassandraManager(hosts: Set[InetSocketAddress] = CassandraProperties.DefaultHosts) extends CassandraManager(hosts) {
  override val livePort = 9142
  private[this] var inited = false
  private[this] var _session: Session = null

  def clusterRef: Cluster = CassandraInitLock.synchronized {
    if (cluster.isClosed) {
      try {
        blocking {
          cluster.connect()
          logger.info("Cluster connection successful")
          cluster
        }
      } catch {
        case NonFatal(e) => {
          if (shouldAttemptReconnect(e)) {
            logger.info(s"Renewing cluster connection after encountering error message: ${e.getMessage}")
            cluster
          } else {
            logger.error("Unable to reconnect to the cluster", e)
            throw new Exception("Unable to recreate cluster connection. Cluster is unavailable", e)
          }
        }
      }
    } else {
      logger.info("Cluster is healthy and connection was made directly")
      cluster
    }
  }

  def cassandraPort(host: InetAddress = getCurrentIp): Int = {
    try {
      new Socket(host.getHostName, livePort)
      livePort
    } catch {
      case ex: IOException => embeddedPort
    }
  }

  def uniformPorts(hosts: Set[InetSocketAddress], port: Int): Set[InetSocketAddress] = {
    hosts.map(item => { new InetSocketAddress(item.getHostName, port) })
  }

  @volatile protected[this] var cluster: Cluster = DBConnector.cluster.build()

  def session: Session = _session

  def initIfNotInited(keySpace: String): Unit = CassandraInitLock.synchronized {
    if (!inited) {
      _session = blocking {
        val s = clusterRef.connect()
        s.execute(createKeySpace(keySpace))
        s
      }
      inited = true
    }
  }
}

private[cassandra] case object CassandraInitLock
```

**Comment by alexflav23** [comment] 2015-06-13 11:22
Hi @elmalto ,

Embedded testing is actually no longer supported in phantom and connectors have been re-written from scratch. We are in the process of publishing a `phantom-sbt` plugin that allows you to start embedded Cassandra directly from SBT, and that will be available in the coming weeks.

Meanwhile, this issue will be closed as it no longer reflects supported features. There is no reliable way to control singleton instantiation from SBT and in multi-build projects + multiple classloaders race conditions occur that break the whole logic, and there seems to be no way around that. It is way `phantom-sbt` was designed by one of our contributors, to address this challenge and fix race conditions.

Regards.

**Closed by alexflav23** 2015-06-13 11:22 UTC
