### ISSUE TITLE
Prepared Statement using DSL

### ISSUE THREAD

**Issue by mmoulou** [websudos/phantom#396] opened 2016-01-11 12:24 UTC
Hello,
I have updated "the version" to phantom 1.20.0, i'm trying to use PreparedStatements with phantom Dsl and i'm facing some issues with insert queries using TTL & with SELECT and UPDATE queries, 

i've the query below: 

insert
      .value(_.accountId, viewByAccount.accountId)
      .value(_.contentId, viewByAccount.contentId)
      .value(_.viewId, viewByAccount.viewId)
      .ttl(ttl)

that I would like to transform to :

insert.p_value(_.accountId, ?).p_value(_.contentId, ?).p_value(_.viewId, ?).ttl(?).prepare()

The issue is that the aforementioned query can't be complied because 'ttl' method doesn't support  '?' symbol

on SELECT & UPDATE queries, 'bind' method has been disappeared, can you plz tell me how can i use preparedStatement on this queries ?

**Comment by alexflav23** [comment] 2016-01-12 17:25
Hi @mmoulou ,

Seems there has been a merge regression that we will address very shortly, many thanks for pointing that out. TTL methods don't yet have a prepared version but that will be added in a future incremental release as well.

Regards,
Flavian

**Comment by alexflav23** [comment] 2016-01-12 17:34
Hi @mmoulou,

It's also worth noting the DSL for prepared statements has slightly changed, and for a very good reason. Have a look (here)[https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/test/scala/com/websudos/phantom/builder/query/prepared/PreparedSelectQueryTest.scala] for examples.

**Comment by alexflav23** [comment] 2016-01-15 14:29
Hi @mmoulou,

This has all been fixed in `1.21.0`, conditional update queries are still not preparable in a typesafe way but we will add that in the next incremental release. This should be live and on Maven Central later today.

Regards,
Flavian

**Comment by alexflav23** [comment] 2016-01-17 22:08
Hi @mmoulou ,

`1.21.0` is now live, prepared TTL binds are not supported though, Cassandra throws an error.

**Closed by alexflav23** 2016-01-17 22:08 UTC

**Comment by fggarcia** [comment] 2016-02-06 06:57
Hi @alexflav23 

can you reopen this issue until cassandra doesn't throw an error?

In case that you don't want, do you suggest me any way to resolve this? Because PreparedStatement is great for get better performance in Batch query.

Thanks.

**Comment by alexflav23** [comment] 2016-02-06 10:12
Hi @fggarcia ,

This has been fixed, a new release will come out today that includes the fixes.

Regards.

**Comment by fggarcia** [comment] 2016-02-06 22:17
Thank you @alexflav23

**Comment by alexflav23** [comment] 2016-02-06 22:23
Hi @fggarcia ,

Try out `1.21.4` on Bintray, that should address this issue.

**Comment by fggarcia** [comment] 2016-02-06 22:55
@alexflav23 in version 1.21.4

insert
    .p_value(_.key, ?)
    .p_value(_.hotel, ?)
    .p_value(_.year, ?)
    .p_value(_.period, ?)
    .p_value(_.cacheKey, ?)
    .p_value(_.datetime, ?)
    .p_value(_.jsonValue, ?)
      .ttl(?)
    .prepare() is not valid. Do I  have an error??

Another question, is it possible that prepared statement is not available for update and select query??

**Comment by alexflav23** [comment] 2016-02-06 22:59
Hi @fggarcia, 

I think if you read the compiler error properly it will tell you there's no preapred `ttl` method. No it's not possible, you are likely misuing the DSL or once again attempting to combine `ttl(?)` which is not possible in Cassandra, it's not a driver side limitation.

Regards.
