### ISSUE TITLE
BigIntColumn seems to be processed as varint

### ISSUE THREAD

**Issue by razvan-** [websudos/phantom#354] opened 2015-11-16 10:14 UTC
When:
object some_big_num extends BigIntColumn(this)

I get:
Value some_big_num is of type bigint, not varint

Maybe because of: 
https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/main/scala/com/websudos/phantom/builder/primitives/Primitive.scala#L326-L328

**Comment by alexflav23** [comment] 2015-11-16 10:25
Hi Razvan,

Thank you for getting in touch, however Cassandra doesn't have a `BigInt` type in its predefined type list, instead it defines `varint` as a variable length integer, or in other words a `BigInt` equivalent. We obviously have tests covering the definition, compilation, storage and retrieval of `BigInt` primitives without error and all I can suggest is that you take a look at the similar tables in the phantom tests, such as [this one](https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/test/scala/com/websudos/phantom/tables/Primitives.scala#L88)

In the future a full stack trace alongside the specifics of reproducing your error might come in handy.

Regards.

**Comment by razvan-** [comment] 2015-11-16 10:31
Hmm. I just started using c* a couple of weeks ago so may be that it got added recently: http://docs.datastax.com/en/cql/3.1/cql/cql_reference/cql_data_types_c.html

**Comment by alexflav23** [comment] 2015-11-16 10:32
Hi,

That seems to be the case, the current version of the Java Driver doesn't even have any support for extracting a `BigInt`, at least not in the version currently behind phantom. I'll chat with someone on their side about this, I'm sure if they released it there's an update in their driver somewhere too.

Thank you for pointing this out.

Regards.

**Comment by razvan-** [comment] 2015-11-16 11:02
Awesome (y)

**Comment by razvan-** [comment] 2015-11-16 12:37
fyi: Seems it matches java's long:
http://docs.datastax.com/en/developer/java-driver/1.0/java-driver/reference/javaClass2Cql3Datatypes_r.html

scala> r
res18: com.datastax.driver.core.Row = Row[s-blahblah, 1, woop]

scala> r.getLong("customer_id")
res17: Long = 1

**Comment by alexflav23** [comment] 2015-11-17 10:11
Hi @razvan-,

So the `varint` is actually the correct type to use. The thing is the Java Driver internally, which extracts the `Row` from the Cassandra response will automatically match the requested extraction against the metadata of the table, so the call to `getVarint` would actually fail should the Cassandra column be something else.

As you don't really want a `BigInt` in the first place from what I understand, why not just stick to a `Long` in the first place? Or please give me more details about your use case.

Regards,
Flavian

**Comment by alexflav23** [comment] 2015-11-18 18:50
Sounds like this issue is no longer a problem, I will close it for now, please let me know if you need further help!

**Closed by alexflav23** 2015-11-18 18:50 UTC
